ApiCrudToDo/Models/ErrorViewModel.cs
namespace ApiCrudToDo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApiCrudToDo/Models/TodoModel.cs
namespace ApiCrudToDo.Models
{
    public class TodoModel
    {
        
        public int id { get; set; }
        
        public string todo {  get; set; }
        public bool completed { get; set; }
        public int userId { get; set; }

        public override string ToString()
        {
            return $"ID: {id}\n Todo: {todo}\n Completed: {completed}\n UserId: {userId}\n ";
        }

    }
}

ApiCrudToDo/Models/TodosList.cs
namespace ApiCrudToDo.Models
{
    public class TodosList
    {
        public List<TodoModel> todos {  get; set; }
    }
}

ApiCrudToDo/Controllers/HomeController.cs
using ApiCrudToDo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ApiCrudToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApiCrudToDo/Controllers/TodoController.cs
using ApiCrudToDo.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ApiCrudToDo.Controllers
{
    public class TodoController : Controller
    {
        private readonly JsonPlaceholderService _jsonPlaceholderService;
        public TodoController(JsonPlaceholderService jsonPlaceholderService) 
        {
            _jsonPlaceholderService = jsonPlaceholderService;
        }

        // GET: TodoController
        public async Task<ActionResult> Index()
        {
            var list = await _jsonPlaceholderService.GetTodosAsync();
            return View(list);
        }

        // GET: TodoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TodoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TodoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TodoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TodoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TodoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TodoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ApiCrudToDo/Controllers/TodoModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApiCrudToDo.Models;
using ApiCrudToDo.Services;

namespace ApiCrudToDo.Controllers
{
    public class TodoModelsController : Controller
    {


        private readonly JsonPlaceholderService _jsonPlaceholderService;
        public TodoModelsController(JsonPlaceholderService jsonPlaceholderService)
        {
            _jsonPlaceholderService = jsonPlaceholderService;
        }

        // GET: TodoModels
        public async Task<IActionResult> Index()
        {
            var list = await _jsonPlaceholderService.GetTodosAsync();
            return View(list);
        }

        // GET: TodoModels/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoModel = await _jsonPlaceholderService.GetTodoAsync(id);
                
            if (todoModel == null)
            {
                return NotFound();
            }

            return View(todoModel);
        }

        // GET: TodoModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TodoModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,todo,completed,userId")] TodoModel todoModel)
        {
            if (ModelState.IsValid)
            {
                
               var newModel =  await _jsonPlaceholderService.CreateTodoAsync(todoModel);
                return RedirectToAction(nameof(Index));
            }
            return View(todoModel);
        }

        // GET: TodoModels/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoModel = await _jsonPlaceholderService.GetTodoAsync(id);
            if (todoModel == null)
            {
                return NotFound();
            }
            return View(todoModel);
        }

        // POST: TodoModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,todo,completed,userId")] TodoModel todoModel)
        {
            if (id != todoModel.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _jsonPlaceholderService.UpdateTodoAsync(id,todoModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    
                }
                return RedirectToAction(nameof(Index));
            }
            return View(todoModel);
        }

        // GET: TodoModels/Delete/5
       /* public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoModel = await _context.TodoModel
                .FirstOrDefaultAsync(m => m.id == id);
            if (todoModel == null)
            {
                return NotFound();
            }

            return View(todoModel);
        }

        // POST: TodoModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var todoModel = await _context.TodoModel.FindAsync(id);
            if (todoModel != null)
            {
                _context.TodoModel.Remove(todoModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TodoModelExists(int id)
        {
            return _context.TodoModel.Any(e => e.id == id);
        }*/
    }
}

ApiCrudToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiCrudToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApiCrudToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Todo" asp-action="Index">ApiCrudToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ApiCrudToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ApiCrudToDo/Views/Todo/Index.cshtml
@model IEnumerable<ApiCrudToDo.Models.TodoModel>;
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="row">
    <div class="col-2">
        <form  asp-action="create" asp-controller="Todo">
            <div class="input-group">

            <input  type="number"  ="userid" value="" placeholder="userid"/>
                <textarea type="text" name="todo" value="" placeholder="todo"></textarea>

                <label>completed?</label>
            <input type="checkbox" name="completed" value="" placeholder="completed"/>
            </div>
        <button class="btn btn-success" type="submit" value="create new" style="width:200px;height:100px" />
        </form>
    </div>

    <div class="col-6" id="postList">
        @foreach(var todo in Model)
        {
            <div>ID:@todo.id</div>
            <div>UserID:@todo.userId</div>
            <div>TODO: @todo.todo</div>
            <div>Completed:@todo.completed</div>
        }
    </div>
</div>

ApiCrudToDo/Views/TodoModels/Create.cshtml
@model ApiCrudToDo.Models.TodoModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TodoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="todo" class="control-label"></label>
                <input asp-for="todo" class="form-control" />
                <span asp-validation-for="todo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="completed" /> @Html.DisplayNameFor(model => model.completed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="userId" class="control-label"></label>
                <input asp-for="userId" class="form-control" />
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ApiCrudToDo/Views/TodoModels/Delete.cshtml
@model ApiCrudToDo.Models.TodoModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.todo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.todo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.completed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ApiCrudToDo/Views/TodoModels/Details.cshtml
@model ApiCrudToDo.Models.TodoModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TodoModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.todo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.todo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.completed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ApiCrudToDo/Views/TodoModels/Edit.cshtml
@model ApiCrudToDo.Models.TodoModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TodoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="todo" class="control-label"></label>
                <input asp-for="todo" class="form-control" />
                <span asp-validation-for="todo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="completed" /> @Html.DisplayNameFor(model => model.completed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="userId" class="control-label"></label>
                <input asp-for="userId" class="form-control" />
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ApiCrudToDo/Views/TodoModels/Index.cshtml
@model IEnumerable<ApiCrudToDo.Models.TodoModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.todo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.completed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.userId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.todo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.completed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.userId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>